const products = [
  {
    productId: 2,
    productName: "product2",
    productPrice: 40,
    quantity: 1,
    productImg: "imgpath",
  },
  {
    productId: 1,
    productName: "product1",
    productPrice: 50,
    quantity: 1,
    productImg: "imgpath",
  },
  {
    productId: 3,
    productName: "product3",
    productPrice: 45,
    quantity: 1,
    productImg: "imgpath",
  },
  {
    productId: 4,
    productName: "product4",
    productPrice: 35,
    quantity: 1,
    productImg: "imgpath",
  },
  {
    productId: 5,
    productName: "product5",
    productPrice: 50,
    quantity: 1,
    productImg: "imgpath",
  },
  {
    productId: 6,
    productName: "product6",
    productPrice: 30,
    quantity: 1,
    productImg: "imgpath",
  },
  {
    productId: 7,
    productName: "product7",
    productPrice: 45,
    quantity: 1,
    productImg: "imgpath",
  },
  {
    productId: 8,
    productName: "product8",
    productPrice: 65,
    quantity: 1,
    productImg: "imgpath",
  },
  {
    productId: 9,
    productName: "product9",
    productPrice: 55,
    quantity: 1,
    productImg: "imgpath",
  },
  {
    productId: 10,
    productName: "product10",
    productPrice: 40,
    quantity: 1,
    productImg: "imgpath",
  },
];
export default products;
